pipeline {
    agent any
    tools {
        jdk 'Java17'    // Jenkins JDK name
        maven 'Maven3'  // Jenkins Maven name
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/kiran-mourya/product-service.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean package -DskipTests=false'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                bat 'start java -jar target\\product-service-1.0-SNAPSHOT.jar'
            }
        }
    }
}
