pipeline {
    agent any

    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Pull the actual application repo
                git branch: 'main', url: 'https://github.com/kiran-mourya/product-service.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deploy') {
            steps {
                bat 'java -jar target\\product-service-1.0-SNAPSHOT.jar'
            }
        }
    }
}
