pipeline {
    agent any

    tools {
            jdk 'Java17'
            maven 'Maven3'
        }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/kiran-mourya/product-service.git'
            }
        }

         stage('Build') {
                    steps {
                        bat 'mvn clean package -DskipTests'
                    }
         }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Trigger Downstream Pipeline') {
            steps {
                build job: 'product-service-jenkins', wait: true
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
